// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Rb9AtAFo1fH7RV6E5EPIY0MAYAgyOkg',
    appId: '1:556870651087:web:d96e1dcad883ceaab8fbba',
    messagingSenderId: '556870651087',
    projectId: 'fitness-tracker-flutter-bcf04',
    authDomain: 'fitness-tracker-flutter-bcf04.firebaseapp.com',
    storageBucket: 'fitness-tracker-flutter-bcf04.firebasestorage.app',
    measurementId: 'G-R8RQPN6N5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUXeOjEaR6WEZVcpAFjytKMzp2hQb1MNM',
    appId: '1:556870651087:android:938568969e69d3b1b8fbba',
    messagingSenderId: '556870651087',
    projectId: 'fitness-tracker-flutter-bcf04',
    storageBucket: 'fitness-tracker-flutter-bcf04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTs3KN9S6bQSbdnXXg76ckQOAAOZPrprc',
    appId: '1:556870651087:ios:6ce6e93486ef253fb8fbba',
    messagingSenderId: '556870651087',
    projectId: 'fitness-tracker-flutter-bcf04',
    storageBucket: 'fitness-tracker-flutter-bcf04.firebasestorage.app',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Rb9AtAFo1fH7RV6E5EPIY0MAYAgyOkg',
    appId: '1:556870651087:web:8d7939de8c55be5bb8fbba',
    messagingSenderId: '556870651087',
    projectId: 'fitness-tracker-flutter-bcf04',
    authDomain: 'fitness-tracker-flutter-bcf04.firebaseapp.com',
    storageBucket: 'fitness-tracker-flutter-bcf04.firebasestorage.app',
    measurementId: 'G-S21NPG8X07',
  );
}
